### ISSUE TITLE
[Query] How would I flatten an array inside an object?

### ISSUE THREAD

**Issue by bluefangs** [dimadeveatii/mongo-dot-notation#7]
Hi,
This is not an issue. I'd just like to know if this is possible:

I have an object:

```
{
"ipv4": {
         "enable": "yes",
         "rule": [
             {
                "flow": {
                    "destinationAddress": "0.0.0.0"
                }
            }
        ]
    }
}
```
I'm looking to produce an output like: 
```
{
       ipv4.enable: yes,
       rule.0.flow.destinationAddress: 0.0.0.0
}
```

Is this possible?

**Comment by dimadeveatii** [comment]
Hi,

Currently array's are set as they are, meaning no flattening is applied inside array's documents.
You can do something like

```javascript
var $ = require('mongo-dot-notation')
var data = {
"ipv4": {
         "enable": "yes",
         "rule": $.$(0).$set({
                "flow": {
                    "destinationAddress": "0.0.0.0"
                }
            })
    }
}

var flat = $.flatten(data)

/* ouputs:
{ 
  $set: {
       'ipv4.enable': yes,
       'ipv4.rule.0': { flow: { destinationAddress: '0.0.0.0' } }
  }
}
*/
````

This will set the first embedded document in the `ipv4.rule` array, however it will replace entire document rather than just updating the `flow.destinationAddress` field.

I might consider adding your request as a feature to be added in the next releases.

**Comment by bluefangs** [comment]
Thanks for the quick turnaround @dimadeveatii 
I happened to find another[ npm package](https://www.npmjs.com/package/mongo-dot-notation) that fits my use case

**Comment by ramirotw** [comment]
hi @bharathkeshav12, I'm interested in that package that you found, do you mind sharing it?

**Comment by lsaether** [comment]
Is this still on the radar to be completed eventually? Would be really helpful for a project I'm working on that has a lot of nested objects in arrays, where I need to update deeply nested values.

**Comment by dimadeveatii** [comment]
Hi @lsaether, this feature was not added yet as there was no real demand. Could you please describe your exact usage and need? Is it the same as described in the initial post?

**Comment by dimadeveatii** [comment]
Happy to announce array support has been added.  
See unit test example:
https://github.com/dimadeveatii/mongo-dot-notation/blob/0c983bf221672e61db3cc2bfaf40e52247ca3320/tests/flatten.spec.ts#L307-L327
