### ISSUE TITLE
Enhancement request: Change dots in key name to \u2024 while using flatten

### ISSUE THREAD

**Issue by Asaf-S** [dimadeveatii/mongo-dot-notation#9]
I think the subject says it all.
When the key name has a dot, using flatten before mongodb.update() will use the first part as the parent of the second part.
The common thing to do it to replace it with this special char which is also a dot: \u2024.
Ref: https://stackoverflow.com/questions/8429318/how-to-use-dot-in-field-name

After testing, the only code change is replacing the following loop in the `lib/flatten.js`:

```
  for(let i = 0, n = keys.length; i < n; i++){
    const key = keys[i] && keys[i].replace(/\./g, '\u2024');
    const newPrefix = !propertyName ? key : (propertyName + '.' + key);
    flatten(updateData, newPrefix, propertyValue[keys[i]]);
  }
```

**Comment by dimadeveatii** [comment]
Well, firstly I don't think that having some special chars like dots in the name of a field is a good idea. This is misleading.
Although I'd suggest that you don not use dots in the name of a field, you might still need it in case you deal with an existing database schema.  

However, this should not be the responsibility of the current package, and your suggestion to replace with `\u2024` might not work in all cases, for all versions of mongo. In this case I'd suggest you take care of the provided field name and replace the dot before you provide it to `flatten`.  

Some other possibility would be to extend `flatten` to accept a transformer function that would allow user to apply a transformation for a field, smth. like:
```js
$.flatten(data, { key: name => name.replace(/\./g, '\u2024') });
```

**Comment by Asaf-S** [comment]
Agreed, so please see this issue as a feature request to allow transformer functions 👍
